import type { CopyTable } from '@/lib/promo/industryCopy/copyTypes';

/**
 * Wording for the templates that run at any time of year.
 *
 * With no occasion to hang the words on, each leans on the trade's own
 * recurring reason to run a campaign — an emergency call-out, a premium line,
 * a consultation.
 */
export const EVERGREEN_COPY: CopyTable = {
  'midnight-neon': {
    'home-trades': {
      title: '<strong>Emergency Call-Out</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>Out in 60 Minutes</strong></span> across the county',
      description: 'After-hours cover for leaks, outages and lockouts. One call and an engineer is on the way.',
      buttonText: 'Call an Engineer',
      timerText: 'Night rate ends in {timer}',
    },
    'retail': {
      title: '<strong>Midnight Flash Drop</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>Buy 1 Get 1</strong></span> on selected lines',
      description: 'Late-night pricing on the pieces people ask for most. Live until the small hours only.',
      buttonText: 'Shop the Drop',
      timerText: 'Flash ends in {timer}',
    },
    'professional': {
      title: '<strong>Out-of-Hours Advice</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>Same-Day Answers</strong></span> on urgent matters',
      description: 'For deadlines that will not wait. Speak to an adviser tonight and know where you stand.',
      buttonText: 'Request a Call',
      timerText: 'Line closes in {timer}',
    },
    'hospitality': {
      title: '<strong>Late Kitchen Tonight</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>Two for One</strong></span> on small plates',
      description: 'Doors open until late with the full menu running. Walk-ins welcome while tables last.',
      buttonText: 'Reserve a Table',
      timerText: 'Kitchen closes in {timer}',
    },
    'wellness': {
      title: '<strong>Late Openings Tonight</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>Evening Slots</strong></span> after work',
      description: 'Appointments running past six for anyone who cannot make the daytime. Book while free.',
      buttonText: 'Grab a Late Slot',
      timerText: 'Last slot in {timer}',
    },
    'automotive': {
      title: '<strong>Out-of-Hours Recovery</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>24 Hour Callout</strong></span> county-wide',
      description: 'Breakdown cover through the night, with recovery and a courtesy car where available.',
      buttonText: 'Call Recovery',
      timerText: 'Night cover ends in {timer}',
    },
    'creative': {
      title: '<strong>Last-Minute Booking</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>Rush Turnaround</strong></span> this week only',
      description: 'A gap has opened in the diary. Quick-turnaround work taken on at short notice.',
      buttonText: 'Claim the Slot',
      timerText: 'Slot goes in {timer}',
    },
    'education': {
      title: '<strong>Evening Classes</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>After-Work Sessions</strong></span> starting soon',
      description: 'Small evening groups for anyone learning around a job. A few places left this term.',
      buttonText: 'Join a Class',
      timerText: 'Enrolment ends in {timer}',
    },
    'property': {
      title: '<strong>Evening Viewings</strong>',
      subtitle: '<span style="font-size: 1.125rem;"><strong>After Six</strong></span> by appointment',
      description: 'Viewings arranged outside working hours, so you can see the place without taking leave.',
      buttonText: 'Book a Viewing',
      timerText: 'Diary closes in {timer}',
    },
  },
  'luxury-gold': {
    'home-trades': {
      title: '<strong>Master Craftsman Service</strong> <span style="font-size:0.8rem;">VETTED TRADES</span>',
      subtitle: 'Time-Served <strong>Trades</strong> for work worth doing once',
      description: 'Heritage skills for restoration and finish work. Fully insured, referenced and guaranteed.',
      buttonText: 'Request a Quote',
      timerText: 'Consultation window closes in {timer}',
    },
    'retail': {
      title: '<strong>Royal Loom Collection</strong> <span style="font-size:0.8rem;">SIGNATURE EDIT</span>',
      subtitle: 'Exclusive <strong>Members Access</strong> to limited drops',
      description: 'Handmade statement pieces with heritage finishes. Priority pricing is live for members.',
      buttonText: 'Enter Private Sale',
      timerText: 'Private window closes in {timer}',
    },
    'professional': {
      title: '<strong>Private Client Service</strong> <span style="font-size:0.8rem;">BY REFERRAL</span>',
      subtitle: 'Direct <strong>Partner Access</strong> no account handlers',
      description: 'Discreet advice for complex affairs, handled by the partner who takes your first call.',
      buttonText: 'Arrange a Meeting',
      timerText: 'Introductions close in {timer}',
    },
    'hospitality': {
      title: '<strong>Chef\'s Table Evenings</strong> <span style="font-size:0.8rem;">TWELVE SEATS</span>',
      subtitle: 'An <strong>Invited Sitting</strong> once a month',
      description: 'Twelve seats, one menu, cooked in front of you. Wine pairing chosen for the evening.',
      buttonText: 'Request a Seat',
      timerText: 'Seats released in {timer}',
    },
    'wellness': {
      title: '<strong>Signature Treatments</strong> <span style="font-size:0.8rem;">PRIVATE SUITE</span>',
      subtitle: 'Exclusive <strong>Suite Access</strong> for the full afternoon',
      description: 'The room, the therapist and the afternoon are yours. Nothing is rushed or shared.',
      buttonText: 'Book the Suite',
      timerText: 'Suite is held for {timer}',
    },
    'automotive': {
      title: '<strong>Marque Specialist Care</strong> <span style="font-size:0.8rem;">FACTORY TRAINED</span>',
      subtitle: 'Factory <strong>Trained Technicians</strong> for prestige marques',
      description: 'Servicing and diagnostics by technicians trained on the marque. Collection arranged.',
      buttonText: 'Arrange Collection',
      timerText: 'Workshop books up in {timer}',
    },
    'creative': {
      title: '<strong>Signature Commission</strong> <span style="font-size:0.8rem;">FOUR A YEAR</span>',
      subtitle: 'Limited to <strong>Four Commissions</strong> each year',
      description: 'A full creative engagement from concept to delivery, with only four taken annually.',
      buttonText: 'Enquire About a Commission',
      timerText: 'Enquiries close in {timer}',
    },
    'education': {
      title: '<strong>One-to-One Tuition</strong> <span style="font-size:0.8rem;">BY ASSESSMENT</span>',
      subtitle: 'Places by <strong>Assessment Only</strong> six pupils a term',
      description: 'Individual tuition with a specialist, following an initial assessment. Six places a term.',
      buttonText: 'Request an Assessment',
      timerText: 'Assessment slots close in {timer}',
    },
    'property': {
      title: '<strong>Signature Venue Hire</strong> <span style="font-size:0.8rem;">EXCLUSIVE USE</span>',
      subtitle: 'Exclusive <strong>Whole-Venue Use</strong> for the full day',
      description: 'The house, the grounds and the team for a single day. One booking at a time, always.',
      buttonText: 'Request Availability',
      timerText: 'Dates released in {timer}',
    },
  },
  'professional-slate': {
    'home-trades': {
      title: '<strong>Commercial Property Maintenance</strong>',
      subtitle: '<span style="font-size:0.9rem;">Planned and reactive cover for managed buildings</span>',
      description: 'Scheduled maintenance and call-out cover for landlords and managing agents. One contact, one invoice.',
      buttonText: 'Request Terms',
      timerText: '{timer} left for contract pricing',
    },
    'retail': {
      title: '<strong>Trade & Wholesale Accounts</strong>',
      subtitle: '<span style="font-size:0.9rem;">Volume pricing for stockists and resellers</span>',
      description: 'Open a trade account for wholesale rates, priority stock allocation and thirty-day terms.',
      buttonText: 'Open an Account',
      timerText: '{timer} left for launch pricing',
    },
    'professional': {
      title: '<strong>Retained Advisory Service</strong>',
      subtitle: '<span style="font-size:0.9rem;">Designed for growing businesses and their boards</span>',
      description: 'Ongoing advice on a fixed monthly fee, so the questions get asked before they become problems.',
      buttonText: 'View Terms',
      timerText: '{timer} left for retainer pricing',
    },
    'hospitality': {
      title: '<strong>Corporate & Private Dining</strong>',
      subtitle: '<span style="font-size:0.9rem;">For boards, away days and client entertaining</span>',
      description: 'Private rooms, set menus and dedicated service for business bookings of eight and above.',
      buttonText: 'Request a Menu',
      timerText: '{timer} left for corporate rates',
    },
    'wellness': {
      title: '<strong>Workplace Wellbeing Programme</strong>',
      subtitle: '<span style="font-size:0.9rem;">On-site sessions for teams and their managers</span>',
      description: 'Regular on-site sessions delivered at your premises, with reporting for HR where required.',
      buttonText: 'View the Programme',
      timerText: '{timer} left for programme pricing',
    },
    'automotive': {
      title: '<strong>Fleet Servicing Contracts</strong>',
      subtitle: '<span style="font-size:0.9rem;">For vans, company cars and managed fleets</span>',
      description: 'Scheduled servicing, MOTs and repairs across your fleet, with one account and one invoice.',
      buttonText: 'Request Fleet Terms',
      timerText: '{timer} left for fleet pricing',
    },
    'creative': {
      title: '<strong>Retained Creative Partner</strong>',
      subtitle: '<span style="font-size:0.9rem;">For brands that need output every month</span>',
      description: 'A fixed monthly retainer covering design, copy and production, with agreed turnaround times.',
      buttonText: 'View Retainer Terms',
      timerText: '{timer} left for retainer pricing',
    },
    'education': {
      title: '<strong>Corporate Training Programmes</strong>',
      subtitle: '<span style="font-size:0.9rem;">Accredited courses delivered at your offices</span>',
      description: 'Accredited training delivered on site, scheduled around your shifts and reported for compliance.',
      buttonText: 'Request a Syllabus',
      timerText: '{timer} left for group pricing',
    },
    'property': {
      title: '<strong>Corporate Venue Partnership</strong>',
      subtitle: '<span style="font-size:0.9rem;">Preferred rates for regular business bookings</span>',
      description: 'Preferential rates and held dates for organisations booking meeting space through the year.',
      buttonText: 'Request Partner Rates',
      timerText: '{timer} left for partner pricing',
    },
  },
  'home-makeover-editorial': {
    'home-trades': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">REFIT</strong> <span style="font-size:0.75rem;">EVENT</span>',
      subtitle: 'One team, one price — <strong>start to finish</strong>. No subcontractors.',
      description: 'Kitchens and bathrooms taken from strip-out to snagging by the same team throughout.',
      buttonText: 'Start My Refit →',
      timerText: 'Fitting dates go in {timer}',
    },
    'retail': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">MAKEOVER</strong> <span style="font-size:0.75rem;">EVENT</span>',
      subtitle: 'Redesign every room — <strong>floor up</strong>. Curated looks, styled for you.',
      description: 'Our stylists picked the pieces that change a room in a single weekend. Shop the whole look.',
      buttonText: 'Start My Makeover →',
      timerText: 'Styling event ends in {timer}',
    },
    'professional': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">RESTRUCTURE</strong> <span style="font-size:0.75rem;">REVIEW</span>',
      subtitle: 'Rebuild the finances — <strong>ground up</strong>. One review, one plan.',
      description: 'A full look at structure, tax and reporting, ending with a plan you can actually follow.',
      buttonText: 'Book the Review →',
      timerText: 'Review slots go in {timer}',
    },
    'hospitality': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">NEW MENU</strong> <span style="font-size:0.75rem;">LAUNCH</span>',
      subtitle: 'Rewritten from — <strong>the ground up</strong>. Same kitchen, new everything.',
      description: 'Every dish reworked with new suppliers and a shorter, sharper list. Tasting nights first.',
      buttonText: 'Book a Tasting →',
      timerText: 'Tasting nights go in {timer}',
    },
    'wellness': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">TRANSFORM</strong> <span style="font-size:0.75rem;">PROGRAMME</span>',
      subtitle: 'Twelve weeks — <strong>start to finish</strong>. Measured, not guessed.',
      description: 'A structured twelve weeks with the same therapist, reviewed fortnightly against real numbers.',
      buttonText: 'Start the Programme →',
      timerText: 'Programme places go in {timer}',
    },
    'automotive': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">RESTORE</strong> <span style="font-size:0.75rem;">PROJECT</span>',
      subtitle: 'Body, paint, interior — <strong>the lot</strong>. Photographed at every stage.',
      description: 'Full restoration handled in one workshop, with progress photographed and shared weekly.',
      buttonText: 'Start My Project →',
      timerText: 'Bay bookings go in {timer}',
    },
    'creative': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">REBRAND</strong> <span style="font-size:0.75rem;">PACKAGE</span>',
      subtitle: 'Identity, site and print — <strong>in one go</strong>. Six weeks, fixed price.',
      description: 'Everything from logo to launch handled together, so nothing is left half-finished.',
      buttonText: 'Start the Rebrand →',
      timerText: 'Project slots go in {timer}',
    },
    'education': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">CATCH UP</strong> <span style="font-size:0.75rem;">PROGRAMME</span>',
      subtitle: 'Assessed, planned — <strong>then taught</strong>. Reported every fortnight.',
      description: 'An assessment, a plan and weekly sessions, with a written update to parents each fortnight.',
      buttonText: 'Book an Assessment →',
      timerText: 'Places go in {timer}',
    },
    'property': {
      title: '<span style="font-size:0.75rem;">THE</span> <strong style="font-size:1.6rem;">REFURBISH</strong> <span style="font-size:0.75rem;">SERVICE</span>',
      subtitle: 'Empty to let — <strong>in six weeks</strong>. Managed throughout.',
      description: 'Refurbishment, compliance and photography handled together so the place lets faster.',
      buttonText: 'Book a Walkthrough →',
      timerText: 'Project slots go in {timer}',
    },
  },
  'all-features': {
    'home-trades': {
      title: '<strong>Weekend Booking Window</strong> <span style="font-size: 0.8rem;">LIMITED SLOTS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>15% OFF</strong></span> + free callout',
      description: 'Weekend work at weekday prices. Quote code <strong>WEEKEND15</strong> when you call.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'retail': {
      title: '<strong>Weekend Festival</strong> <span style="font-size: 0.8rem;">LIMITED DROP</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>35% OFF</strong></span> + free delivery',
      description: 'A full weekend of reductions across the range. Use <strong>COZY35</strong> before it closes.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'professional': {
      title: '<strong>Free Consultation Week</strong> <span style="font-size: 0.8rem;">LIMITED SLOTS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>£0</strong></span> for the first hour',
      description: 'One free hour with an adviser, no obligation. Quote <strong>FIRSTHOUR</strong> to book.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'hospitality': {
      title: '<strong>Weekend Set Menu</strong> <span style="font-size: 0.8rem;">LIMITED COVERS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>£25</strong></span> for three courses',
      description: 'Three courses at one price, Friday to Sunday. Mention <strong>WEEKEND25</strong> when booking.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'wellness': {
      title: '<strong>Weekend Treatment Event</strong> <span style="font-size: 0.8rem;">LIMITED SLOTS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>30% OFF</strong></span> + a free add-on',
      description: 'Two days of reduced pricing on every treatment. Quote <strong>RESET30</strong> to book.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'automotive': {
      title: '<strong>Weekend Service Event</strong> <span style="font-size: 0.8rem;">LIMITED BAYS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>£89</strong></span> + free valet',
      description: 'Full service at one price across the weekend. Quote <strong>SERVICE89</strong> to book a bay.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'creative': {
      title: '<strong>Mini Session Weekend</strong> <span style="font-size: 0.8rem;">LIMITED SLOTS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>£150</strong></span> + five edited images',
      description: 'Twenty-minute sessions across one weekend only. Quote <strong>MINI150</strong> to book.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'education': {
      title: '<strong>Open Weekend</strong> <span style="font-size: 0.8rem;">LIMITED PLACES</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>£0</strong></span> for a taster session',
      description: 'Come and try any class free across the weekend. Quote <strong>TASTER</strong> to reserve.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
    'property': {
      title: '<strong>Open House Weekend</strong> <span style="font-size: 0.8rem;">LIMITED VIEWINGS</span>',
      subtitle: '<span style="font-size: 0.85rem;">Flat</span> <span style="font-size: 1.35rem;"><strong>£0 fees</strong></span> + same-day decisions',
      description: 'Open viewings all weekend with fees waived. Quote <strong>OPENHOUSE</strong> on arrival.',
      buttonText: 'Reveal My Offer',
      timerText: 'Offer ends in {timer}',
    },
  },
  'earthy-cozy': {
    'home-trades': {
      title: '<strong>Warm Home Week</strong> <span style="font-size:0.8rem;">INSULATION</span>',
      subtitle: 'Draughts, lofts and lagging, sorted in a day',
      description: 'Small jobs that make a house noticeably warmer, done in a single visit and priced upfront.',
      buttonText: 'Book a Warm-Up',
      timerText: 'Warm home week ends in {timer}',
    },
    'retail': {
      title: '<strong>Cozy Home Week</strong> <span style="font-size:0.8rem;">CALM LIVING</span>',
      subtitle: 'Natural tones, soft textures, and calm spaces',
      description: 'Warm materials and quiet colours, chosen to make a room feel settled rather than styled.',
      buttonText: 'Build My Cozy Space',
      timerText: 'Cozy week ends in {timer}',
    },
    'professional': {
      title: '<strong>Quiet Quarter Offer</strong> <span style="font-size:0.8rem;">NO RUSH</span>',
      subtitle: 'Unhurried advice, taken at a sensible pace',
      description: 'Our quietest months, which means longer meetings and answers that are not squeezed in.',
      buttonText: 'Book an Unhurried Hour',
      timerText: 'Quiet quarter ends in {timer}',
    },
    'hospitality': {
      title: '<strong>Fireside Suppers</strong> <span style="font-size:0.8rem;">SLOW FOOD</span>',
      subtitle: 'Long tables, slow cooking, no rush to leave',
      description: 'Braises, bread and a fire lit from four. Tables held for the whole evening, not turned.',
      buttonText: 'Book by the Fire',
      timerText: 'Fireside tables go in {timer}',
    },
    'wellness': {
      title: '<strong>Slow Treatment Week</strong> <span style="font-size:0.8rem;">UNHURRIED</span>',
      subtitle: 'Ninety minutes, no clock-watching, no upsell',
      description: 'Longer appointments at the usual price, because rushing is what makes treatments useless.',
      buttonText: 'Book Ninety Minutes',
      timerText: 'Slow week ends in {timer}',
    },
    'automotive': {
      title: '<strong>Winter Comfort Check</strong> <span style="font-size:0.8rem;">COLD MORNINGS</span>',
      subtitle: 'Heating, battery and screenwash, all checked',
      description: 'The things that matter on a cold morning, checked properly while you have a coffee.',
      buttonText: 'Book a Comfort Check',
      timerText: 'Winter checks end in {timer}',
    },
    'creative': {
      title: '<strong>Slow Craft Sessions</strong> <span style="font-size:0.8rem;">NO RUSH</span>',
      subtitle: 'Unhurried shoots, shot on film where you like',
      description: 'Half-day sessions with time to get it right, rather than an hour and a shot list.',
      buttonText: 'Book a Half Day',
      timerText: 'Slow sessions end in {timer}',
    },
    'education': {
      title: '<strong>Small Group Term</strong> <span style="font-size:0.8rem;">SIX PER CLASS</span>',
      subtitle: 'Six pupils a class, so nobody gets lost',
      description: 'Deliberately small groups where every child is heard, taught by one consistent coach.',
      buttonText: 'Reserve a Place',
      timerText: 'Small group places go in {timer}',
    },
    'property': {
      title: '<strong>Quiet Retreat Hire</strong> <span style="font-size:0.8rem;">NO NEIGHBOURS</span>',
      subtitle: 'Space, silence, and nobody else on site',
      description: 'Somewhere genuinely quiet for a retreat or a small gathering, with exclusive use throughout.',
      buttonText: 'Check Quiet Dates',
      timerText: 'Quiet dates go in {timer}',
    },
  },
};
