import type { CopyTable } from '@/lib/promo/industryCopy/copyTypes';

/**
 * Wording for the templates tied to a date in the year.
 *
 * The occasion is the fixed half and the trade is the variable one: Christmas
 * for a garage is a winter check, for a restaurant a festive menu, for an
 * accountant a year-end review.
 */
export const SEASONAL_COPY: CopyTable = {
  'christmas-evergreen-gold': {
    'home-trades': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">CHRISTMAS</strong> <span style="font-size:0.9rem;">Check</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>£30 OFF</strong></span> <span style="font-size:0.8rem;">+ free safety report</span>',
      description: 'Get the boiler and wiring checked before the family arrives. Engineers booking up fast.',
      buttonText: '🎁 Book Before Christmas',
      timerText: 'Engineer diary closes in {timer}',
    },
    'retail': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">CHRISTMAS</strong> <span style="font-size:0.9rem;">Sale</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Up to 50% OFF</strong></span> <span style="font-size:0.8rem;">+ free gift wrapping</span>',
      description: 'Everything you need for the tree, the table and the stockings, wrapped and ready to go.',
      buttonText: '🎁 Claim Holiday Deal',
      timerText: 'Last posting in {timer}',
    },
    'professional': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">YEAR END</strong> <span style="font-size:0.9rem;">Review</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Free Review</strong></span> <span style="font-size:0.8rem;">+ fixed-fee quote</span>',
      description: 'Close the books before the break. Bring your paperwork in and start January clear.',
      buttonText: '🎁 Book Year-End Review',
      timerText: 'Office closes in {timer}',
    },
    'hospitality': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">CHRISTMAS</strong> <span style="font-size:0.9rem;">Menu</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Three Courses</strong></span> <span style="font-size:0.8rem;">+ a drink on arrival</span>',
      description: 'Festive menu now taking bookings, for parties of any size. Private room available.',
      buttonText: '🎁 Book the Table',
      timerText: 'Party dates go in {timer}',
    },
    'wellness': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">CHRISTMAS</strong> <span style="font-size:0.9rem;">Edit</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Gift Vouchers</strong></span> <span style="font-size:0.8rem;">+ a free add-on</span>',
      description: 'Party-season appointments and gift vouchers that always fit. Late openings all December.',
      buttonText: '🎁 Buy a Voucher',
      timerText: 'December fills in {timer}',
    },
    'automotive': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">WINTER</strong> <span style="font-size:0.9rem;">Check</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Free Check</strong></span> <span style="font-size:0.8rem;">+ tyres from £45</span>',
      description: 'Battery, tyres and antifreeze checked before the cold sets in. Ten minutes, no booking.',
      buttonText: '🎁 Book Winter Check',
      timerText: 'Offer ends in {timer}',
    },
    'creative': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">CHRISTMAS</strong> <span style="font-size:0.9rem;">Slots</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Two Dates Left</strong></span> <span style="font-size:0.8rem;">before the new year</span>',
      description: 'Festive shoots and campaign work still possible if booked this week. Diary closing soon.',
      buttonText: '🎁 Check the Diary',
      timerText: 'Last dates go in {timer}',
    },
    'education': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">HOLIDAY</strong> <span style="font-size:0.9rem;">Club</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Full Week</strong></span> <span style="font-size:0.8rem;">+ sibling discount</span>',
      description: 'Holiday clubs running through the break, with qualified coaches and hot lunches daily.',
      buttonText: '🎁 Reserve a Place',
      timerText: 'Places go in {timer}',
    },
    'property': {
      title: '<span style="font-size:0.75rem;">❄ THE</span> <strong style="font-size:1.6rem;">CHRISTMAS</strong> <span style="font-size:0.9rem;">Party</span>',
      subtitle: '<span style="font-size:1.3rem;"><strong>Rooms From £250</strong></span> <span style="font-size:0.8rem;">+ decorations included</span>',
      description: 'Party dates still available for December, dressed and staffed. Deposit holds the date.',
      buttonText: '🎁 Hold My Date',
      timerText: 'December books up in {timer}',
    },
  },
  'newyear-champagne-confetti': {
    'home-trades': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR, NEW BATHROOM</span>',
      subtitle: '<span style="font-size:0.85rem;">Book now for</span> <span style="font-size:1.35rem;"><strong>£500 OFF fitting</strong></span>',
      description: 'Start the year with the job you have been putting off. January fitting dates open now.',
      buttonText: 'Book a Survey 🥂',
      timerText: 'January dates go in {timer}',
    },
    'retail': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR SALE</span>',
      subtitle: '<span style="font-size:0.85rem;">Pop into savings —</span> <span style="font-size:1.35rem;"><strong>up to 60% OFF</strong></span>',
      description: 'Everything from last season reduced to clear. New stock lands the moment it is gone.',
      buttonText: 'Toast to the Deal 🥂',
      timerText: 'Countdown to midnight: {timer}',
    },
    'professional': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR, NEW BOOKS</span>',
      subtitle: '<span style="font-size:0.85rem;">Start clean with</span> <span style="font-size:1.35rem;"><strong>three months free</strong></span>',
      description: 'Move your bookkeeping across in January and the first quarter is on us. No tie-in.',
      buttonText: 'Start the Switch 🥂',
      timerText: 'Offer closes in {timer}',
    },
    'hospitality': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR MENU</span>',
      subtitle: '<span style="font-size:0.85rem;">See it in with</span> <span style="font-size:1.35rem;"><strong>a five-course sitting</strong></span>',
      description: 'New Year sitting with a glass on arrival and a room that stays open past midnight.',
      buttonText: 'Book the Night 🥂',
      timerText: 'Countdown to midnight: {timer}',
    },
    'wellness': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR, NEW ROUTINE</span>',
      subtitle: '<span style="font-size:0.85rem;">Begin with</span> <span style="font-size:1.35rem;"><strong>six sessions for four</strong></span>',
      description: 'Book a block in January and two sessions are free. Same therapist throughout.',
      buttonText: 'Start in January 🥂',
      timerText: 'Block pricing ends in {timer}',
    },
    'automotive': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR SERVICE</span>',
      subtitle: '<span style="font-size:0.85rem;">Full service from</span> <span style="font-size:1.35rem;"><strong>£99 all in</strong></span>',
      description: 'Start the year with everything checked, topped up and stamped. Courtesy car included.',
      buttonText: 'Book It In 🥂',
      timerText: 'January slots go in {timer}',
    },
    'creative': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NOW TAKING BOOKINGS</span>',
      subtitle: '<span style="font-size:0.85rem;">Diary opens with</span> <span style="font-size:1.35rem;"><strong>early-bird pricing</strong></span>',
      description: 'Next year is open. Book before the end of January and hold this year’s rates.',
      buttonText: 'Hold My Date 🥂',
      timerText: 'Early pricing ends in {timer}',
    },
    'education': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">SPRING TERM ENROLLING</span>',
      subtitle: '<span style="font-size:0.85rem;">Join with</span> <span style="font-size:1.35rem;"><strong>a free first session</strong></span>',
      description: 'Spring term places are open. Come to one session before deciding, at no cost.',
      buttonText: 'Reserve a Place 🥂',
      timerText: 'Term starts in {timer}',
    },
    'property': {
      title: '<span style="font-size:2rem;"><strong>2026</strong></span> <span style="font-size:0.8rem;">NEW YEAR, NEW ADDRESS</span>',
      subtitle: '<span style="font-size:0.85rem;">Move in with</span> <span style="font-size:1.35rem;"><strong>no admin fees</strong></span>',
      description: 'January listings are live and admin fees are waived on anything agreed this month.',
      buttonText: 'Browse Listings 🥂',
      timerText: 'Fee waiver ends in {timer}',
    },
  },
  'autumn-harvest': {
    'home-trades': {
      title: '<strong>Autumn Boiler Service</strong> <span style="font-size:0.8rem;">BEFORE THE COLD</span>',
      subtitle: '<span style="font-size:0.85rem;">Up to</span> <span style="font-size:1.35rem;"><strong>£40 OFF</strong></span> a full service',
      description: 'Get it looked at before the first cold snap, when every engineer in the county is booked.',
      buttonText: 'Book a Service',
      timerText: 'Autumn slots end in {timer}',
    },
    'retail': {
      title: '<strong>Autumn Harvest Sale</strong> <span style="font-size:0.8rem;">AUTUMN EDIT</span>',
      subtitle: '<span style="font-size:0.85rem;">Up to</span> <span style="font-size:1.35rem;"><strong>40% OFF</strong></span> autumn ranges',
      description: 'Warm tones, heavier fabrics and everything you need as the evenings start drawing in.',
      buttonText: 'Shop Autumn Edit',
      timerText: 'Harvest deal ends in {timer}',
    },
    'professional': {
      title: '<strong>Autumn Tax Review</strong> <span style="font-size:0.8rem;">BEFORE JANUARY</span>',
      subtitle: '<span style="font-size:0.85rem;">From</span> <span style="font-size:1.35rem;"><strong>£150</strong></span> fixed fee',
      description: 'Sort the return now rather than over Christmas. Fixed fee agreed before we start.',
      buttonText: 'Book a Review',
      timerText: 'Autumn pricing ends in {timer}',
    },
    'hospitality': {
      title: '<strong>Autumn Menu Is In</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: '<span style="font-size:0.85rem;">Two courses</span> <span style="font-size:1.35rem;"><strong>£22</strong></span> midweek',
      description: 'Game, root vegetables and something warming by the fire. Midweek sittings now open.',
      buttonText: 'Book a Table',
      timerText: 'Midweek offer ends in {timer}',
    },
    'wellness': {
      title: '<strong>Autumn Reset</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: '<span style="font-size:0.85rem;">Save</span> <span style="font-size:1.35rem;"><strong>25%</strong></span> on a course of four',
      description: 'Skin and body take a knock as the weather turns. A short course puts it right.',
      buttonText: 'Book a Course',
      timerText: 'Course pricing ends in {timer}',
    },
    'automotive': {
      title: '<strong>Autumn Safety Check</strong> <span style="font-size:0.8rem;">BEFORE THE COLD</span>',
      subtitle: '<span style="font-size:0.85rem;">Free</span> <span style="font-size:1.35rem;"><strong>22-Point Check</strong></span> no booking needed',
      description: 'Tyres, battery, lights and wipers checked before the dark evenings arrive. Ten minutes.',
      buttonText: 'Drop In Today',
      timerText: 'Free checks end in {timer}',
    },
    'creative': {
      title: '<strong>Autumn Campaign Slots</strong> <span style="font-size:0.8rem;">AUTUMN EDIT</span>',
      subtitle: '<span style="font-size:0.85rem;">Save</span> <span style="font-size:1.35rem;"><strong>15%</strong></span> on autumn shoots',
      description: 'Autumn light is the best of the year. Two shoot dates left before the clocks change.',
      buttonText: 'Check the Diary',
      timerText: 'Autumn dates go in {timer}',
    },
    'education': {
      title: '<strong>Autumn Term Places</strong> <span style="font-size:0.8rem;">NOW ENROLLING</span>',
      subtitle: '<span style="font-size:0.85rem;">Save</span> <span style="font-size:1.35rem;"><strong>10%</strong></span> on a full term',
      description: 'A few places left across the autumn timetable. Pay for the term and save on the block.',
      buttonText: 'Reserve a Place',
      timerText: 'Term starts in {timer}',
    },
    'property': {
      title: '<strong>Autumn Lettings</strong> <span style="font-size:0.8rem;">AVAILABLE NOW</span>',
      subtitle: '<span style="font-size:0.85rem;">From</span> <span style="font-size:1.35rem;"><strong>£850 pcm</strong></span> bills included',
      description: 'Properties available before the winter. Move-in dates through October and November.',
      buttonText: 'Browse Available',
      timerText: 'Listings refresh in {timer}',
    },
  },
  'summer-sunset-splash': {
    'home-trades': {
      title: '<strong>Summer Garden Refresh</strong> <span style="font-size:0.8rem;">OUTDOOR WORK</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Garden Jobs Booked Now</strong></span> <span style="font-size:0.8rem;">decking, fencing, patios</span>',
      description: 'The dry weeks are the ones to use. Outdoor work booked in while the ground is firm.',
      buttonText: 'Get a Summer Quote 🌊',
      timerText: 'Summer diary closes in {timer}',
    },
    'retail': {
      title: '<strong>Summer Sunset Sale</strong> <span style="font-size:0.8rem;">SEASON EDIT</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Buy 2 Get 1 Free</strong></span> <span style="font-size:0.8rem;">on all summer lines</span>',
      description: 'Lighter pieces in brighter shades, priced to move before the season turns. Stock is limited.',
      buttonText: 'Dive Into Savings 🌊',
      timerText: 'Heat ends in {timer}',
    },
    'professional': {
      title: '<strong>Quiet Season Rates</strong> <span style="font-size:0.8rem;">AUGUST ONLY</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Quiet-Season Rates</strong></span> <span style="font-size:0.8rem;">through August</span>',
      description: 'August is our quietest month and the rates reflect it. Same team, same work, less waiting.',
      buttonText: 'Book While Quiet 🌊',
      timerText: 'Summer rates end in {timer}',
    },
    'hospitality': {
      title: '<strong>The Garden Is Open</strong> <span style="font-size:0.8rem;">ALL SUMMER</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Garden Now Open</strong></span> <span style="font-size:0.8rem;">and the grill is on</span>',
      description: 'Long tables outside, cold drinks and the grill running from noon. No booking needed before six.',
      buttonText: 'Grab a Table 🌊',
      timerText: 'Garden closes in {timer}',
    },
    'wellness': {
      title: '<strong>Summer Ready in Four</strong> <span style="font-size:0.8rem;">FOUR WEEKS</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Summer Ready in Four</strong></span> <span style="font-size:0.8rem;">sessions, not months</span>',
      description: 'A short, sensible plan before the holiday, with a therapist who will not oversell it.',
      buttonText: 'Start This Week 🌊',
      timerText: 'Summer offer ends in {timer}',
    },
    'automotive': {
      title: '<strong>Holiday Road Check</strong> <span style="font-size:0.8rem;">BEFORE YOU GO</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Free Holiday Check</strong></span> <span style="font-size:0.8rem;">before you set off</span>',
      description: 'Tyres, coolant and air-con checked before the long drive. Booked in and out the same morning.',
      buttonText: 'Book Before You Go 🌊',
      timerText: 'Holiday checks end in {timer}',
    },
    'creative': {
      title: '<strong>Golden Hour Sessions</strong> <span style="font-size:0.8rem;">SUMMER DATES</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Summer Dates Open</strong></span> <span style="font-size:0.8rem;">golden hour only</span>',
      description: 'Evening shoots through July and August, when the light does most of the work for us.',
      buttonText: 'Check Availability 🌊',
      timerText: 'Summer dates go in {timer}',
    },
    'education': {
      title: '<strong>Summer Camp Weeks</strong> <span style="font-size:0.8rem;">SCHOOL HOLIDAYS</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Summer Camp Weeks</strong></span> <span style="font-size:0.8rem;">full days, hot lunch</span>',
      description: 'Week-long camps through the holidays with qualified coaches and everything provided.',
      buttonText: 'Book a Week 🌊',
      timerText: 'Camp places go in {timer}',
    },
    'property': {
      title: '<strong>Summer Party Dates</strong> <span style="font-size:0.8rem;">OUTDOOR VENUE</span>',
      subtitle: '<span style="font-size:1.4rem;"><strong>Summer Party Dates</strong></span> <span style="font-size:0.8rem;">marquee included</span>',
      description: 'Outdoor dates still open across July and August, with the marquee and staffing included.',
      buttonText: 'Check Dates 🌊',
      timerText: 'Summer dates go in {timer}',
    },
  },
  'easter-pastel-egg': {
    'home-trades': {
      title: '<strong>Easter Break Repairs</strong> <span style="font-size:0.8rem;">LONG WEEKEND</span>',
      subtitle: '<span style="font-size:0.85rem;">Book over Easter for</span> <span style="font-size:1.4rem;"><strong>£50 OFF</strong></span> <span style="font-size:0.85rem;">+ a free callout</span>',
      description: 'The long weekend is the easiest time to have work done. Two teams available across the break.',
      buttonText: 'Book the Weekend 🥚',
      timerText: 'Easter slots go in {timer}',
    },
    'retail': {
      title: '<strong>Easter Sale</strong> <span style="font-size:0.8rem;">SPRING EDIT</span>',
      subtitle: '<span style="font-size:0.85rem;">Hop in for</span> <span style="font-size:1.4rem;"><strong>30% OFF</strong></span> <span style="font-size:0.85rem;">+ free delivery</span>',
      description: 'Spring stock reduced across the long weekend, with everything sent out the same day.',
      buttonText: 'Unwrap the Offer 🥚',
      timerText: 'Basket closes in {timer}',
    },
    'professional': {
      title: '<strong>Sorted Before Easter</strong> <span style="font-size:0.8rem;">NEW QUARTER</span>',
      subtitle: '<span style="font-size:0.85rem;">Book before Easter for</span> <span style="font-size:1.4rem;"><strong>Free Setup</strong></span> <span style="font-size:0.85rem;">+ first month free</span>',
      description: 'Get the paperwork moving before the break so the new quarter starts in order.',
      buttonText: 'Start Before Easter 🥚',
      timerText: 'Offer closes in {timer}',
    },
    'hospitality': {
      title: '<strong>Easter Sunday Lunch</strong> <span style="font-size:0.8rem;">FAMILY TABLES</span>',
      subtitle: '<span style="font-size:0.85rem;">Easter Sunday from</span> <span style="font-size:1.4rem;"><strong>£26</strong></span> <span style="font-size:0.85rem;">+ egg hunt for children</span>',
      description: 'Roast, pudding and an egg hunt in the garden. Family tables filling up fast.',
      buttonText: 'Book Easter Sunday 🥚',
      timerText: 'Tables go in {timer}',
    },
    'wellness': {
      title: '<strong>An Easter Treat</strong> <span style="font-size:0.8rem;">LONG WEEKEND</span>',
      subtitle: '<span style="font-size:0.85rem;">Easter treat —</span> <span style="font-size:1.4rem;"><strong>20% OFF</strong></span> <span style="font-size:0.85rem;">+ a free add-on</span>',
      description: 'A quiet hour to yourself over the long weekend, with an extra treatment on the house.',
      buttonText: 'Book a Treat 🥚',
      timerText: 'Weekend slots go in {timer}',
    },
    'automotive': {
      title: '<strong>Bank Holiday Check</strong> <span style="font-size:0.8rem;">BEFORE YOU DRIVE</span>',
      subtitle: '<span style="font-size:0.85rem;">Before you drive off —</span> <span style="font-size:1.4rem;"><strong>Free Check</strong></span> <span style="font-size:0.85rem;">+ £20 off a service</span>',
      description: 'A quick check before the bank holiday traffic. Tyres, oil and coolant, while you wait.',
      buttonText: 'Book Before You Go 🥚',
      timerText: 'Easter checks end in {timer}',
    },
    'creative': {
      title: '<strong>Blossom Season Shoots</strong> <span style="font-size:0.8rem;">EASTER DATES</span>',
      subtitle: '<span style="font-size:0.85rem;">Spring shoots from</span> <span style="font-size:1.4rem;"><strong>£250</strong></span> <span style="font-size:0.85rem;">+ ten edited images</span>',
      description: 'Bright, soft light and a garden full of blossom. Two weekend dates left over Easter.',
      buttonText: 'Book a Session 🥚',
      timerText: 'Easter dates go in {timer}',
    },
    'education': {
      title: '<strong>Easter Holiday Club</strong> <span style="font-size:0.8rem;">FULL WEEKS</span>',
      subtitle: '<span style="font-size:0.85rem;">Easter club —</span> <span style="font-size:1.4rem;"><strong>Full Week</strong></span> <span style="font-size:0.85rem;">+ sibling discount</span>',
      description: 'Holiday club through the Easter break, with coaches, lunch and everything provided.',
      buttonText: 'Book the Week 🥚',
      timerText: 'Places go in {timer}',
    },
    'property': {
      title: '<strong>Easter Open Viewings</strong> <span style="font-size:0.8rem;">ALL WEEKEND</span>',
      subtitle: '<span style="font-size:0.85rem;">Easter viewings —</span> <span style="font-size:1.4rem;"><strong>All Weekend</strong></span> <span style="font-size:0.85rem;">+ no admin fees</span>',
      description: 'Open viewings across the long weekend, with admin fees waived on anything agreed.',
      buttonText: 'Book a Viewing 🥚',
      timerText: 'Viewings close in {timer}',
    },
  },
  'spring-bloom': {
    'home-trades': {
      title: '<strong>Spring Garden Refresh</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: 'Fencing, <strong>decking and turf</strong> booked in now',
      description: 'Get the outside sorted before summer. Ground is workable and the diary is still open.',
      buttonText: 'Get a Spring Quote',
      timerText: 'Spring dates end in {timer}',
    },
    'retail': {
      title: '<strong>Spring Refresh</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: 'Bring <strong>fresh colours</strong> and lighter pieces home',
      description: 'Pastels, florals and lighter fabrics to brighten every corner as the season turns.',
      buttonText: 'Shop The Bloom Edit',
      timerText: 'Spring deal ends in {timer}',
    },
    'professional': {
      title: '<strong>New Tax Year Setup</strong> <span style="font-size:0.8rem;">APRIL START</span>',
      subtitle: 'Start the year with <strong>clean books</strong> and fixed monthly fees',
      description: 'Get the new tax year set up properly from April, with fees agreed before we begin.',
      buttonText: 'Book a Setup Call',
      timerText: 'April slots end in {timer}',
    },
    'hospitality': {
      title: '<strong>Spring Menu Is In</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: 'Lighter plates, <strong>longer evenings</strong> and the garden open',
      description: 'New season menu with the garden open again and tables outside from midday.',
      buttonText: 'Book a Table',
      timerText: 'Garden tables go in {timer}',
    },
    'wellness': {
      title: '<strong>Spring Reset</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: 'Book a <strong>course of four</strong> and save a fifth',
      description: 'Skin, sleep and energy all shift with the season. A short course helps them settle.',
      buttonText: 'Book a Course',
      timerText: 'Course pricing ends in {timer}',
    },
    'automotive': {
      title: '<strong>Spring Service Offer</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: 'Full service and <strong>free valet</strong> booked together',
      description: 'Winter is hard on a car. Service, check and a proper clean before the better weather.',
      buttonText: 'Book a Service',
      timerText: 'Spring offer ends in {timer}',
    },
    'creative': {
      title: '<strong>Spring Sessions Open</strong> <span style="font-size:0.8rem;">NEW SEASON</span>',
      subtitle: 'Blossom, <strong>golden light</strong> and long evenings',
      description: 'Spring is the best light of the year for outdoor work. Weekend dates going quickly.',
      buttonText: 'Check Availability',
      timerText: 'Spring dates go in {timer}',
    },
    'education': {
      title: '<strong>Summer Term Enrolling</strong> <span style="font-size:0.8rem;">NOW OPEN</span>',
      subtitle: 'Small groups, <strong>real progress</strong> and a free first session',
      description: 'Summer term places are open across the timetable. Come to one session before deciding.',
      buttonText: 'Reserve a Place',
      timerText: 'Term starts in {timer}',
    },
    'property': {
      title: '<strong>Spring Viewings</strong> <span style="font-size:0.8rem;">NOW OPEN</span>',
      subtitle: 'See it <strong>at its best</strong> with the garden in bloom',
      description: 'Spring is when these places show best. Weekend viewings now open across the portfolio.',
      buttonText: 'Arrange a Viewing',
      timerText: 'Weekend slots go in {timer}',
    },
  },
};
